import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { buildPersistText, PERSIST_SOURCE } from './persist.js'

/**
 * A persistence hook is two pieces: a standalone runtime script that prints the
 * skill's compact core to stdout, and a UserPromptSubmit entry in settings.json
 * that runs it. Claude Code adds a UserPromptSubmit hook's stdout to the model's
 * context for that turn, so the reminder is re-asserted on every prompt without
 * the model having to remember it.
 *
 * The runtime is written self-contained next to the skill, so it keeps working
 * if the skillsmith checkout moves. To keep it honest it inlines the very same
 * buildPersistText source used by `skillsmith persist`, and a test asserts the
 * two produce identical output.
 */

const MARKER = 'skillsmith:persist'

/** Source of the standalone hook runtime for one skill. */
export function generateHookScript(skillMdPath: string): string {
  const abs = resolve(skillMdPath).replace(/\\/g, '\\\\')
  return `#!/usr/bin/env node
// ${MARKER} — re-injects a skill's core on every UserPromptSubmit.
// Generated by skillsmith. Safe to delete; run \`skillsmith hook --remove\` to unwire it.
import { readFileSync } from 'node:fs'

const SKILL = '${abs}'

${PERSIST_SOURCE}

try {
  process.stdout.write(buildPersistText(readFileSync(SKILL, 'utf8')))
} catch {
  // A persistence reminder must never block a prompt; stay silent on any error.
}
`
}

export interface HookCommand {
  type: 'command'
  command: string
}

interface Settings {
  hooks?: {
    UserPromptSubmit?: Array<{ matcher?: string; hooks: HookCommand[] }>
    [event: string]: unknown
  }
  [key: string]: unknown
}

function hookCommandFor(scriptPath: string): string {
  // Quote the path for the non-interactive shell the hook runs in.
  return `node "${resolve(scriptPath)}"`
}

async function readSettings(path: string): Promise<Settings> {
  try {
    const raw = await readFile(path, 'utf8')
    return raw.trim() ? (JSON.parse(raw) as Settings) : {}
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {}
    throw new Error(`Could not read ${path}: ${err instanceof Error ? err.message : String(err)}`)
  }
}

/** Merge a UserPromptSubmit entry for this script, idempotently. */
export function mergeHook(settings: Settings, scriptPath: string): { settings: Settings; added: boolean } {
  const command = hookCommandFor(scriptPath)
  const hooks = (settings.hooks ??= {})
  const list = (hooks.UserPromptSubmit ??= [])

  const present = list.some((entry) => entry.hooks?.some((h) => h.command === command))
  if (present) return { settings, added: false }

  list.push({ hooks: [{ type: 'command', command }] })
  return { settings, added: true }
}

/** Remove any UserPromptSubmit entry that runs this script. */
export function unmergeHook(settings: Settings, scriptPath: string): { settings: Settings; removed: boolean } {
  const command = hookCommandFor(scriptPath)
  const list = settings.hooks?.UserPromptSubmit
  if (!list) return { settings, removed: false }

  const kept = list
    .map((entry) => ({ ...entry, hooks: entry.hooks?.filter((h) => h.command !== command) ?? [] }))
    .filter((entry) => entry.hooks.length > 0)

  const removed = kept.length !== list.length
  if (removed) settings.hooks!.UserPromptSubmit = kept
  return { settings, removed }
}

export interface InstallResult {
  scriptPath: string
  settingsPath: string
  added: boolean
  command: string
}

export async function installHook(opts: {
  skillDir: string
  settingsPath: string
}): Promise<InstallResult> {
  const skillMd = join(opts.skillDir, 'SKILL.md')
  const scriptPath = join(opts.skillDir, 'persist.mjs')

  await writeFile(scriptPath, generateHookScript(skillMd), 'utf8')

  const settings = await readSettings(opts.settingsPath)
  const { added } = mergeHook(settings, scriptPath)
  await mkdir(dirname(opts.settingsPath), { recursive: true })
  await writeFile(opts.settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf8')

  return { scriptPath, settingsPath: opts.settingsPath, added, command: hookCommandFor(scriptPath) }
}

export async function removeHook(opts: {
  skillDir: string
  settingsPath: string
}): Promise<{ removed: boolean; settingsPath: string }> {
  const scriptPath = join(opts.skillDir, 'persist.mjs')
  const settings = await readSettings(opts.settingsPath)
  const { removed } = unmergeHook(settings, scriptPath)
  if (removed) await writeFile(opts.settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf8')
  return { removed, settingsPath: opts.settingsPath }
}

/** The runtime output the hook would inject right now, for a dry run. */
export async function previewPersist(skillDir: string): Promise<string> {
  const raw = await readFile(join(skillDir, 'SKILL.md'), 'utf8')
  return buildPersistText(raw)
}
